# --- Настройки файла и бэкапов ---
excel_file_path: "tracker.xlsx"
backup_folder: "backups"

# --- Настройки таблицы ---
# Укажите, в какой строке находится каждая категория.
# Это надежнее, чем полагаться на порядок.
categories:
  обучение: 2
  нетворкинг: 3
  аудитория: 4
  контент: 5
  спорт: 6
  семья: 7
  проекты: 8

# --- Настройки команд ---
# Здесь мы определяем, какие слова соответствуют какой категории.
# Это решает проблему частичного совпадения.
# "ключ" - это то, что пойдет в лог, "значения" - то, что ищем в речи.
category_aliases:
  обучение: ["обучение"]
  нетворкинг: ["нетворкинг"]
  аудитория: ["аудитория"]
  контент: ["контент"]
  спорт: ["спорт", "трезвость", "здоровье"]
  семья: ["семья", "личная жизнь", "духовность"]
  проекты: ["проекты"]

# Значение, которое будет ставиться в ячейку
point_value: 1

# --- Настройки Whisper ---
whisper:
  model_size: "base" # Варианты: tiny, base, small, medium, large. "base" - хороший баланс скорости и качества.
  language: "ru"     # Язык для распознавания.